listen:
  host: 0.0.0.0
  port: 8080
postgres:
  database: postgres
  host: postgresql
  port: 5432
  username: postgres
  password: victoriassecret
  ssl_mode: disable
  max_attempts: 5
redis:
  host: redis
  port: 6379
  password:
  database: 0
  expires: 3600 #in second
  max_attempts: 5
